version: '3.8'

services:
  tourGuide:
    depends_on:
      - gpsUtil
      - rewardCentral
      - tripPricer
    image: tourguide
    ports:
      - "8080:8080"
    restart: always

  gpsUtil:
    image: gpsutil
    ports:
      - "8081:8081"
    restart: always

  rewardCentral:
    image: rewardcentral
    ports:
      - "8082:8082"
    restart: always

  tripPricer:
    image: trippricer
    ports:
      - "8083:8083"
    restart: always
